print("create your character!")
name =input("what is your charecter called?")

age =input("how old is your character?")
streanths =input("what are your character's strengths?")
weaknesses =input("what are your characters weaknesses?")
print("your characters name is",name)
print("your character is",age,"years old")
print("strengths:", strengths)
print(name,"says, 'thanks for creating me!'")
